const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  darkMode: "class",
  content: [
    "./app/views/**/*.{erb,haml,html,slim}",
    "./app/helpers/**/*.rb",
    "./app/javascript/**/*.js",
    "./app/assets/stylesheets/**/*.css",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                  "#f2ca50",
        "primary-container":        "#d4af37",
        "primary-fixed":            "#ffe088",
        "primary-fixed-dim":        "#e9c349",
        "on-primary":               "#3c2f00",
        "on-primary-container":     "#554300",
        "on-primary-fixed":         "#241a00",
        "on-primary-fixed-variant": "#574500",
        "inverse-primary":          "#735c00",
        "secondary":                "#dfb7ff",
        "secondary-container":      "#6c11af",
        "secondary-fixed":          "#f1daff",
        "secondary-fixed-dim":      "#dfb7ff",
        "on-secondary":             "#4b007e",
        "on-secondary-container":   "#d5a4ff",
        "on-secondary-fixed":       "#2d004f",
        "on-secondary-fixed-variant": "#690bac",
        "tertiary":                 "#ffbfb8",
        "tertiary-container":       "#ff968c",
        "tertiary-fixed":           "#ffdad6",
        "tertiary-fixed-dim":       "#ffb4ac",
        "on-tertiary":              "#690007",
        "on-tertiary-container":    "#90000e",
        "on-tertiary-fixed":        "#410003",
        "on-tertiary-fixed-variant":"#92030f",
        "surface":                  "#121416",
        "surface-dim":              "#121416",
        "surface-bright":           "#37393b",
        "surface-container-lowest": "#0c0e10",
        "surface-container-low":    "#1a1c1e",
        "surface-container":        "#1e2022",
        "surface-container-high":   "#282a2c",
        "surface-container-highest":"#333537",
        "surface-variant":          "#333537",
        "surface-tint":             "#e9c349",
        "on-surface":               "#e2e2e5",
        "on-surface-variant":       "#d0c5af",
        "inverse-surface":          "#e2e2e5",
        "inverse-on-surface":       "#2f3133",
        "background":               "#121416",
        "on-background":            "#e2e2e5",
        "outline":                  "#99907c",
        "outline-variant":          "#4d4635",
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.75rem",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["Noto Serif", ...defaultTheme.fontFamily.serif],
        body:     ["Manrope", ...defaultTheme.fontFamily.sans],
        label:    ["Manrope", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [],
};
